# $XDG_CONFIG_HOME/alacritty/alacritty.toml
[general]
import = [
    "themes/solarized_light.toml"
]
[env]
NEW_TERMINAL_SESSION = "true"
[window]
# Window title, default "Alacritty"
#title = "Alacritty"
dynamic_title = true
[font]
# Font size, default 11.25
size = 11.25
normal = {family = "Noto Sans Mono"}
offset = {x = 0, y = -4}
[terminal]
#program = "/bin/zsh"
#args = ["-l"]
